Blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from BlogApp import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^all_posts/$', views.PostView.as_view(), name='all_posts'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^category/(?P<id>[0-9]+)/post/(?P<pk>[0-9]+)/$', views.ReadMore.as_view(), name='read_more'),
    url(r'^register/$', views.UserRegister.as_view(), name='register'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^add_category/$', views.AddCategory.as_view(), name='add_category'),
    url(r'^category/(?P<pk>[0-9]+)/add_post/$', views.AddPost.as_view(), name='add_post'),
    url(r'^category/(?P<id>[0-9]+)/post/(?P<pk>[0-9]+)/post_like/$', views.PostLike.as_view(), name='post_like'),
    url(r'^category/(?P<id>[0-9]+)/post/(?P<pk>[0-9]+)/post_dislike/$', views.PostDisLike.as_view(),
        name='post_dislike'),
    url(r'^category/(?P<id>[0-9]+)/post/(?P<pk>[0-9]+)/comment_like/(?P<comment_id>[0-9]+)/$', views.CommentLike.as_view(),
        name='comment_like'),
    url(r'^category/(?P<id>[0-9]+)/post/(?P<pk>[0-9]+)/comment_dislike/(?P<comment_id>[0-9]+)/$',
        views.CommentDisLike.as_view(),
        name='comment_dislike'),
    url(r'^category/(?P<id>[0-9]+)/post/(?P<pk>[0-9]+)/comment_delete/(?P<comment_id>[0-9]+)/$',
        views.DeleteComment.as_view(),
        name='delete_comment'),
    url(r'^category/(?P<id>[0-9]+)/post_delete/(?P<pk>[0-9]+)/$', views.DeletePost.as_view(), name='delete_post'),
    url(r'^category/(?P<id>[0-9]+)/update_post/(?P<pk>[0-9]+)/$', views.UpdatePost.as_view(), name='update_post'),
    url(r'^category/(?P<id>[0-9]+)/post/(?P<pk>[0-9]+)/update_comment/(?P<comment_id>[0-9]+)/$',
        views.UpdateComment.as_view(),
        name='update_comment'),
    url(r'^profile/(?P<id>[0-9]+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'^delete_category/(?P<pk>[0-9]+)/$', views.DeleteCategory.as_view(), name='delete_category'),
    url(r'^api/', include('drf.urls', namespace='rest_framework'))
]

drf/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from drf import views

router = routers.DefaultRouter()
router.register(r'user', views.UserViewSet, base_name="user")
router.register(r'category', views.CategoryViewSet, base_name="category")
router.register(r'post', views.PostViewSet, base_name="post")
router.register(r'comment', views.CommentViewSet, base_name="comment")


urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^post/(?P<id>[0-9]+)/like/$', views.PostLikeViewSet.as_view({'get': 'get'}), name='post_like'),
    url(r'^post/(?P<id>[0-9]+)/dislike/$', views.PostDisLikeViewSet.as_view({'get': 'get'}), name='post_dislike'),
    url(r'^comment/(?P<id>[0-9]+)/like/$', views.CommentLikeViewSet.as_view({'get': 'get'}), name='comment_like'),
    url(r'^comment/(?P<id>[0-9]+)/dislike/$', views.CommentDisLikeViewSet.as_view({'get': 'get'}),
        name='comment_dislike'),
    url(r'^auth/$', views.AuthView.as_view({'post': 'post', 'delete': 'destroy'}), name='auth_view'),

]

BlogApp/models.py
from __future__ import unicode_literals


from django.contrib.auth.models import User
from django.db import models

# Create your models here.

from django.utils.six import python_2_unicode_compatible



@python_2_unicode_compatible
class Category(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


@python_2_unicode_compatible
class Post(models.Model):
    author = models.ForeignKey(User, default='')
    post_of_category = models.ForeignKey(Category)

    post_title = models.TextField(max_length=200)
    post_text = models.TextField(max_length=500)
    num_of_like = models.IntegerField(default=0)
    num_of_dislike = models.IntegerField(default=0)
    created_date = models.DateTimeField( auto_now_add=True)
    updated_date = models.DateTimeField( auto_now_add=True)

    def __str__(self):
        return self.post_text


@python_2_unicode_compatible
class Comment(models.Model):
    author = models.ForeignKey(User, default='')
    post_of_comment = models.ForeignKey(Post)

    comment_text = models.TextField(max_length=200)
    number_of_like = models.IntegerField(default=0)
    number_of_dislike = models.IntegerField(default=0)
    created_date = models.DateTimeField( auto_now_add=True)
    updated_date = models.DateTimeField( auto_now_add=True)

    def __str__(self):
        return self.comment_text

templates/add_category.html
{% extends 'master.html' %}
{% block content %}



<form action="" method="post">
        {% csrf_token %}
        <br>
        {{ category_form }}
        
    <input type="submit" value="Save" />

</form>

{% endblock %}

templates/add_post.html
{% extends 'master.html' %}

{% block content %}



<form action="" method="post">
    {% csrf_token %}
    <br>
{{ post_form }}
        <input type="submit" value="Save" />

</form>

{% endblock %}

templates/detail.html
{#<div style="width: auto; height: 5px; background: #333"> </div>#}

<html xmlns="http://www.w3.org/1999/html">


<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>

<body style="margin: 0">
<div style="background-color: #333333 ; width: 100% ; height: 120px">
    <br>
    <h2><b style="color: chocolate; padding-left: 25px"> {{ category.title }} </b></h2>
    <p style="color: white">
        <a href="{% url 'index' %} " style="color:white ;  padding-left: 25px"> Home </a>
            {% if user.is_authenticated %}
                | <a href="{% url 'add_post' category.id %} " style="color:white ;"> Add Post</a>
                <span style="float: right;  padding-right: 25px">
                    Hoşgeldiniz {{ request.user.username }}
                    | <a href="{% url 'logout' %} " style="color:white ; "> Logout </a>
                </span>

            {% else %}
                | <a href="{% url 'register' %}" style="color:white ;">Sign in</a> |
                <a href="{% url 'login' %}" style="color:white ;" >Login</a>
                {% endif %}
    </p>
</div>




{% if category.post_set %}
    {% for cm in category.post_set.all %}
         <h3><p style="color:darkgrey"> &emsp;{{ cm.post_title }} </p> </h3>


         <p class="bg-warning">   &emsp;&emsp;{{ cm.post_text|slice:":300" }}
             <a href="{% url 'read_more' category.id cm.id %}"> read more ... </a>
          </p>
        <hr/>
    {% endfor %}
{% else %}
    <p>no post</p>
{% endif %}

</body>
</html>

templates/index.html
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
     <style>
        ul,li{list-style-type: none;}
    </style>
</head>


<body style="margin: 0">


<div style="background-color: #333333 ; width: 100% ; height: 120px">
    <br>
    <h2><b style="color: chocolate; padding-left: 25px"> MY BLOG </b></h2>
    <p style="color: white">
        <a href="{% url 'index' %} " style="color:white ; padding-left: 25px "> Home </a>

        {% if request.user.is_authenticated %}
            <span style="float: right">
                    Hoşgeldiniz {{ request.user.username }} |
                    <a href="{% url 'logout' %} " style="color:white ; padding-right: 25px ">Logout</a>
                </span>
            | <a href="{% url 'profile' user.id %} " style="color:white ;"> Profile </a>
            {% if request.user.is_superuser %}
                | <a href="{% url 'add_category' %} " style="color:white ;"> Add Category</a>
            {% endif %}
        {% else %}
           | <a href="{% url 'register' %}" style="color:white ;">Sign in</a> |
            <a href="{% url 'login' %}" style="color:white ;" >Login</a>
        {% endif %}


    </p>
</div>

<h3><p style="color: darkgrey">&emsp;<b> CATEGORIES </b></p> </h3>
{% if categories %}
    <ul>
        {% for category in categories %}
            <br>
            <a href="{% url 'detail' category.id %}"> {{ category.title }} </a>
                {% if request.user.is_superuser  %}
                    <a href="{% url 'delete_category' category.id %}"> X </a>
                {% endif %}
            <br>
        {% endfor %}
    </ul>
{% else %}

    <p>There are no categories. </p>
{% endif %}

<br/>


<hr/>

<h3><p style="color: darkgrey">&emsp;<b> POSTS </b></p> </h3>

{% for pst in posts %}
    <br/>

    <p class="bg-warning"> &emsp;&emsp; {{ pst.post_text |slice:":300" }}
        <a href="{% url 'read_more' pst.post_of_category.id pst.id %}"> read more ... </a>
        <br/></p>

{% endfor %}


</body>

</html>

templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Is anyone getting tired of repeatedly entering the header over and over?? -->


    </head>

    <body>
        <h1>Login </h1>

        <form  action="" method="post">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />

            <input type="submit" value="Login" />
        </form>

    </body>
</html>

templates/master.html
<a href="{% url 'index' %}">Home Page</a>

{% block content %}

{% endblock %}

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
     <style>
        ul,li{list-style-type: none;}
    </style>
</head>
<body style="margin: 0" >

<div style="background-color: #333333 ; width: 100% ; height: 120px">
    <br>
    <h2><b style="color: chocolate; padding-left: 25px"> {{ member }} </b></h2>
    <p style="color: white">
        <a href="{% url 'index' %} " style="color:white ;  padding-left: 25px"> Home </a>
            {% if user.is_authenticated %}
                <span style="float: right;  padding-right: 25px">
                    Hoşgeldiniz {{ user.username }}
                    | <a href="{% url 'logout' %} " style="color:white ; "> Logout </a>
                </span>

            {% else %}
                | <a href="{% url 'register' %}" style="color:white ;">Sign in</a> |
                <a href="{% url 'login' %}" style="color:white ;" >Login</a>
                {% endif %}
    </p>
</div>


<h3><p style="color: darkgrey">&emsp;<b> POSTS </b></p> </h3>

    {% if post %}
        {% for p in post %}
             <br/>
                <h3><p style="color:darkgrey"> &emsp; {{ p.post_title }} </h3> </p>
                <p class="bg-warning"> &emsp;&emsp; {{ p.post_text |slice:":300" }}
                <a href="{% url 'read_more' p.post_of_category_id p.id %}"> read more ... </a>
                <br/></p>
                <hr/>

        {% endfor %}

    {% else %}
         <p>There is no post</p>
    {% endif %}



<h3><p style="color: darkgrey">&emsp;<b> COMMENTS </b></p> </h3>

    {% if comment %}
        {% for c in comment %}
             <br/>
            <h3><p style="color:darkgrey"> &emsp; {{ c.post_of_comment.post_of_category }} </h3> </p>
                <p class="bg-warning"> &emsp;&emsp; {{ c.comment_text |slice:":300" }}
                <a href="{% url 'read_more' c.post_of_comment.post_of_category_id c.post_of_comment.id %}"> read more ... </a>
                <br/></p>
            <hr/>

        {% endfor %}

    {% else %}
         <p>There is no comment</p>
    {% endif %}


</body>
</html>

templates/read_more.html
<!DOCTYPE html>
<html lang="en">
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
     <style>
        ul,li{list-style-type: none;}
    </style>
</head>

<body style="margin: 0">


<div style="background-color: #333333 ; width: 100% ; height: 120px">
    <br>
    <h2><a href="{% url 'detail' category.id %} " style="color:chocolate ;padding-left: 25px ;" class="a"> {{ category.title }} </a></h2>
    <p style="color: white">
        <a href="{% url 'index' %} " style="color:white ;padding-left: 25px "> Home </a>
        {% if user.is_authenticated %}
            <span style="float: right; padding-right: 25px">
                Hoşgeldiniz {{ request.user.username }}
                | <a href="{% url 'logout' %} " style="color:white ; padding-right: 25px "> Logout </a>
            </span>
        {% endif %}
    </p>
</div>




<div style="background-color:beige ; width: 100% ; height: 300px; padding-top: 20px">
    <p><h3> &emsp;{{ post.post_title }}</h3></br>
        <p>     &emsp;      {{post.post_text}}</p>

            <br>
            <br>
           &emsp; Author: <a href="{% url 'profile' post.author.id %}"> {{ post.author }} </a>  <br>
           &emsp; Likes : {{ post.num_of_like }} | Dislikes : {{ post.num_of_dislike }}<br>
           &emsp; Published date : {{ post.created_date }} <br>
            &emsp; Updated date : {{ post.updated_date }}
                        <br> <br> <br>
            &emsp;{% if user.is_authenticated or user.is_superuser %}
                    <b><a href="{% url 'post_like' category.id post.pk %}"> Like </a> |
                    <a href="{% url 'post_dislike' category.id post.pk %}"> Dislike </a>
                    {% if post.author == request.user or user.is_superuser %}
                    | <a href="{% url 'update_post'  category.id post.pk %}"> Update </a>  |
                    <a href="{% url 'delete_post' category.id post.pk %}"> Delete </a>
                {% endif %}
         </b>
    </p>



</div>







    <hr/>





    <form action="" method="post">
        {% csrf_token %}
        <br>
        &emsp; {{ comment_form }}
        <input type="submit" value="Save"/>

    </form>


{% endif %}
<hr/>
<h4><p style="color: darkgrey">&emsp;<b> Comments </b></p> </h4>
<hr/>
{% if post.comment_set %}
    {% for cm in post.comment_set.all %}

        <p> &emsp; {{ cm.comment_text }} <br> <br>

            &emsp; Likes: {{ cm.number_of_like }} | Dislikes: {{ cm.number_of_dislike }} <br>
            &emsp; Created Date: {{ cm.created_date }} <br>
            &emsp; Updated Date: {{ cm.updated_date }} <br>
            &emsp; Commented by: <a href="{% url 'profile' cm.author.id %}"> {{ cm.author }} </a>  <br></p>

        {% if user.is_authenticated %}

           &emsp; <b><a href="{% url 'comment_like' category.id post.pk cm.id %}">Like</a> |
                <a href="{% url 'comment_dislike'  category.id post.pk cm.id %}">Dislike</a>
                {% if cm.author == request.user or user.is_superuser %}
                    |  <a href="{% url 'delete_comment'  category.id post.pk cm.id %}"> Delete </a> |
                    <a href="{% url 'update_comment'  category.id post.pk cm.id %}"> Update </a>

                {% endif %}

            </b>

        {% endif %}
        <hr/>
    {% endfor %}
{% else %}
    <p> NO COMMENTS !</p>
{% endif %}


</body>
</html>

templates/register.html
{% extends 'master.html' %}
{% block content %}



<form action="" method="post">
    {% csrf_token %}
     <br>
    {{ user_form.as_p }}
        <input type="submit" value="Save" />

</form>

{% endblock %}

templates/update_comment.html
{% extends 'master.html' %}

{% block content %}



<form action="" method="post">
    {% csrf_token %}
    <br>
        {{ comment_form }}
        <input type="submit" value="Save" />

</form>

{% endblock %}

templates/update_post.html
{% extends 'master.html' %}

{% block content %}



<form action="" method="post">
    {% csrf_token %}
    <br>
        {{ post_form }}
        <input type="submit" value="Save" />

</form>

{% endblock %}